version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing app dependencies...
      - echo Run "apt-get install"...
      - apt-get update -y && apt-get install -y libsasl2-dev libldap2-dev
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 7)
      - DATAHUB_VERSION=${COMMIT_HASH}
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI_SERVER=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Entered the build phase...
      - echo Building the Docker image...
      - cd docker
      - DOCKER_BUILDKIT=1 docker-compose -f docker-compose.ecr.yml build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Pushing the Docker image...
      - docker-compose -f docker-compose.ecr.yml push
cache:
  paths:
    - '/root/.gradle/caches/**/*'
