source:
  type: "file"
  config:
    filename: "/bootstrap_mce.json"

sink:
  type: "datahub-kafka"
  config:
    connection:
      bootstrap: broker:29092
      schema_registry_url: "http://schema-registry:8081"
